baseurl: /mythjune@github.com

markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: mythjune
url: http://mythjune.github.io
description: Stars in Sand
github: mythjune
gravatar_url: http://img3.douban.com/icon/u1261234-1.jpg

