baseurl: /wangybehere@github.com

markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: wangybehere
url: http://wangybehere.github.io
description: IN GOD WE TRUST 
github: wangybehere
gravatar_url: http://www.gravatar.com/avatar/e7a95885528074f5c7bd13373ae73d97.png

